2021-02-06 10:18:38,292 - combine.py[line: 215] - ERROR: http://172.16.85.35:8000/api/eac_info/get_state/BEOL-PA-N8-301/ HTTPConnectionPool(host='172.16.85.35', port=8000): Max retries exceeded with url: /api/eac_info/get_state/BEOL-PA-N8-301/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x07D6D7F0>, 'Connection to 172.16.85.35 timed out. (connect timeout=5)'))
2021-02-06 10:18:44,303 - combine.py[line: 215] - ERROR: http://172.16.85.35:8000/api/eac_info/get_state/BEOL-PA-N8-301/ HTTPConnectionPool(host='172.16.85.35', port=8000): Max retries exceeded with url: /api/eac_info/get_state/BEOL-PA-N8-301/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x07D6D880>, 'Connection to 172.16.85.35 timed out. (connect timeout=5)'))
2021-02-06 10:18:50,313 - combine.py[line: 215] - ERROR: http://172.16.85.35:8000/api/eac_info/get_state/BEOL-PA-N8-301/ HTTPConnectionPool(host='172.16.85.35', port=8000): Max retries exceeded with url: /api/eac_info/get_state/BEOL-PA-N8-301/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x07D6DD78>, 'Connection to 172.16.85.35 timed out. (connect timeout=5)'))
2021-02-06 10:18:51,323 - combine.py[line: 245] - INFO: ÍË³ö...
